### ISSUE TITLE
Program quitting halfway through starting

### ISSUE THREAD

**Issue by ButtSavage** [Yankee-the-gamer/Multi_Roblox_AFK#1]
Idk what i did or if it just stopped working but everytime i open main.exe now (ran as admin) it quits halfway through before getting to "run autoclicker y/n" is there a way to fix this? To specify this happens on a universal time and not stands awakening (fixed by opening program before playing, oops)

**Comment by Yankee-the-gamer** [comment]
I don't know that an error like that exist nor do I have any idea how you fixed it.
What works, just works, I guess?
